# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Cory Rylan, Software Developer and Front End Engineer 
email: 
description: > # My name is Cory Rylan. 
  I am a Software Developer and Front End Engineer. 
  I specialize in creating fast, scalable, and responsive web applications. 
  I work daily with JavaScript, Angular, JQuery, CSS3, Sass and HTML5.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://coryrylan.firebaseapp.com" # the base hostname & protocol for your site
twitter_username: splintercode
github_username:  splintercode

# Build settings
markdown: kramdown
highlighter: null